dailyjob/authsystem/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static

app_name = "authsystem"


urlpatterns = [
    path("register_customer/",register_customer,name='register_customer'),
    path("register_labour/",register_labour,name='register_labour'),
    path("login_attempt/",login_attempt,name='login_attempt'),
    path('verify/<auth_token>',verify,name='verify'),
    path("", index, name="index"),
    path("logout_view/",logout_view,name='logout_view'),
    path("change_password/",change_password,name='change_password'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dailyjob/chat/urls.py
from django.urls import path
from . import views

app_name = "chat"

urlpatterns = [
    path("room/", views.chat_room, name="chat_room"),
    path("delete/<int:labour_id>/<int:customer_id>/", views.delete_chat, name="delete_chat"),
]

dailyjob/customer/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static


app_name = 'customer'


urlpatterns = [
    path("home/",home,name='home'),
    path("book/<id>",book,name='book'),
    path("cart/",cart,name='cart'),
    path("delete_booking/<id>",delete_booking,name='delete_booking'),
    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dailyjob/dailyjob/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('authsystem/', include('authsystem.urls')),
    path('customer/', include('customer.urls')),
    path('labour/', include('labour.urls')),
    path('location/', include('location.urls')),
    path('chat/', include('chat.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dailyjob/labour/urls.py
from django.urls import path
from .views import *

app_name = "labour"


urlpatterns = [
    path("home/",home,name='home'),
    path("approve/<id>",approve,name='delete_booking'),
    path("delete/<id>",delete,name='delete_booking'),
    path("addjob/",addjob,name='addjob'),
    ]

dailyjob/location/urls.py
from django.urls import path
from .views import *

app_name = "location"


urlpatterns = [
    path('map_view/',map_view,name='map_view'),
]

dailyjob/authsystem/models.py
from django.db import models

# Create your models here.

class Labour(models.Model):
    username = models.CharField(max_length=100)
    password = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=10)
    place = models.CharField(max_length=100)
    image = models.ImageField(upload_to='media/images/')
    auth_token = models.CharField(max_length=100)
    is_verified = models.BooleanField(default=False)
    verification=models.BooleanField(default=False)

    def __str__(self):
        return f"{self.name}"


class Profession(models.Model):
    labour=models.ForeignKey(Labour, on_delete=models.CASCADE)
    profession=models.CharField(max_length=100)
    fees = models.CharField(max_length=10)


    def __str__(self):
        return f"{self.labour.name} - {self.profession}"


class Date(models.Model):
    labour=models.ForeignKey(Labour, on_delete=models.CASCADE)
    date = models.DateField(unique=True)

    def __str__(self):
        return f"{self.labour.name} - {self.date}"


class Customer(models.Model):
    username = models.CharField(max_length=100)
    password = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=10)
    address=models.TextField()
    image = models.ImageField(upload_to='images/')
    auth_token = models.CharField(max_length=100)
    is_verified = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.name}"

dailyjob/authsystem/views.py
from django.shortcuts import render,redirect
from .models import *
import uuid
from django.contrib import messages
from django.conf import settings
from django.core.mail import send_mail


# Create your views here.
def index(request):
    return render(request,"authsystem/index.html")

def login_attempt(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        role = request.POST.get('role')
        request.session['username']=username
        request.session['role']=role

        if role == 'customer':
            customer_obj = Customer.objects.filter(username=username,password=password).first()
            if customer_obj:
                if customer_obj.is_verified: 
                    return redirect('/customer/home/')
                else :
                    messages.error(request,'Account is not verified check your mail')
            else :
                messages.error(request,'Invalid Username or Password')
        else:
            labour_obj = Labour.objects.filter(username=username,password=password).first()
            if labour_obj:
                if labour_obj.is_verified :
                    if labour_obj.verification:
                        request.session['labour_id'] = labour_obj.id
                        return redirect('/labour/home/')
                    else:
                        messages.error(request,'You not a autherized user contact admin for verification')
                else:
                    messages.error(request,'Account is not verified check your mail')
            else:
                messages.error(request,'Invalid Username or Password')

    return render(request,"authsystem/login.html")

def register_customer(request):
    alert_flag = False
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        name = request.POST.get('name')
        phone_number = request.POST.get('phone_number')
        address = request.POST.get('address')
        # image = request.FILES['image']
        image = request.FILES.get('image', None)

        auth_token = str(uuid.uuid4())
        customer_obj=Customer(username=username,password=password,name=name,phone_number=phone_number,address=address,auth_token=auth_token,image=image)
        exsist_customer = Customer.objects.filter(username=username).first()
        if exsist_customer:
            messages.error(request,'Username is already taken')
        else:
            customer_obj.save()
            alert_flag = True

        send_mail_after_registration(username,auth_token)


    return render(request,"authsystem/register_customer.html", {'alert_flag': alert_flag})


def register_labour(request):
    alert_flag = False
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        name = request.POST.get('name')
        phone_number = request.POST.get('phone_number')
        profession = request.POST.get('profession')
        place = request.POST.get('place')
        fees = request.POST.get('fees')
        other_profession = request.POST.get('other_profession')
        image = request.FILES['image']  # Access the uploaded file

        auth_token = str(uuid.uuid4())
        exsist_labour = Labour.objects.filter(username=username).first()
        if exsist_labour:
            messages.error(request, "Username is already taken")
        else:
            # Save Labour without fees
            labour_obj = Labour(
                username=username,
                password=password,
                name=name,
                phone_number=phone_number,
                place=place,
                image=image,
                auth_token=auth_token
            )
            labour_obj.save()

            # Save Profession with fees
            profession_to_save = other_profession if profession == 'other' else profession
            Profession.objects.create(
                labour=labour_obj,
                profession=profession_to_save,
                fees=fees
            )

            alert_flag = True
            send_mail_after_registration(username, auth_token)

    return render(request, "authsystem/register_labour.html", {'alert_flag': alert_flag})

def send_mail_after_registration(username, token):
    subject = 'Click the link for your account verification'
    message = f'Hi past the link to verify your account http://127.0.0.1:8000/authsystem/verify/{token}'
    email_from = settings.EMAIL_HOST_USER
    recipient_list = [username]
    send_mail(subject,message,email_from,recipient_list)

def verify(request, auth_token):
    # Check for a profile in both Customer and Labour models
    profile_obj = Customer.objects.filter(auth_token=auth_token).first() or Labour.objects.filter(auth_token=auth_token).first()

    if profile_obj:
        profile_obj.is_verified = True
        profile_obj.save()
        # Redirect based on the type of profile (Customer or Labour)
        if isinstance(profile_obj, Customer):
            return redirect('/customer/home/')
        elif isinstance(profile_obj, Labour):
            return redirect('/labour/home/')
    else:
        messages.error(request, 'Invalid verification link')
        return redirect('index')

def logout_view(request):
   request.session.flush()
   return redirect('/authsystem/login_attempt/')

def change_password(request):
    username = request.session.get('username')
    role = request.session.get('role')
    if not username:
        return redirect('login_attempt')

    user = None
    user_type = None

    # Try to identify the user type
    try:
        user = Customer.objects.get(username=username)
        user_type = 'customer'
    except Customer.DoesNotExist:
        try:
            user = Labour.objects.get(username=username)
            user_type = 'labour'
        except Labour.DoesNotExist:
            return redirect('login_attempt')

    if request.method == 'POST':
        new_password = request.POST.get('password')

        user.password = new_password
        user.save()
        return redirect('login_attempt')  # Adjust as needed
    return render(request, "authsystem/change_password.html",{'role':role})

dailyjob/authsystem/templates/authsystem/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <title>
      {% block title %}

      {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'authsystem/css/base.css' %}" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% block head %}

    {% endblock %}
  </head>
  <body>
      <div class="logoo">
        <img src="{% static 'authsystem/img/logo.png' %}" alt="logo" class="logo" />
      </div>
    <div class="content">
      {% block content %}

      {% endblock %}
    </div>
  </body>
</html>

dailyjob/authsystem/templates/authsystem/change_password.html
{% extends 'authsystem/base.html' %}

{% load static %}

{% block title %}Change password{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'authsystem/css/change_password.css' %}">
{% endblock %}
{% block content %}

<div class="icons">
    {% if role == "labour" %}
    <a href="{% url 'labour:home' %}"><button class="buttonss">Home</button></a>
    <a href="{% url 'labour:addjob' %}"><button class="buttonss">Add Job</button></a>
    <a href="{% url 'location:map_view' %}"><button class="buttonss">Map</button></a>
    <a href="{% url 'chat:chat_room' %}"><button class="buttonss">Chat</button></a>
    <a href="{% url 'authsystem:logout_view' %}"><button class="buttonss">Log Out</button></a>


    {% else %}
    <a href="{% url 'customer:home' %}"><button class="buttonss">Home</button></a>
    <a href="{% url 'customer:cart' %}"><button class="buttonss">Cart</button></a>
    <a href="{% url 'location:map_view' %}"><button class="buttonss">Map</button></a>
    <a href="{% url 'chat:chat_room' %}"><button class="buttonss">Chat</button></a>
    <a href="{% url 'authsystem:logout_view' %}"><button class="buttonss">Log Out</button></a>

    {% endif %}
</div>


<div class="login-box">
    <h2>Change Password</h2>

    <form method="post">
        {% csrf_token %}

        <div class="user-box">
            <input type="text" name="password" required="" id="password">
            <label>Password</label>
        </div>
        <div class="user-box">
            <input type="password" name="confirmPassword" required="" id="confirmPassword">
            <label>Confirm Password</label>
        </div>
        <button type="submit" class="animated-button" id="submit">
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            Submit
        </button>
    </form>


</div>

<script src="{% static 'authsystem/js/change_password.js' %}"></script>

{% endblock %}

dailyjob/authsystem/templates/authsystem/index.html
{% extends 'authsystem/base.html' %}

{% load static %}

{% block title %}Index{% endblock %}

{% block head %}    
<link rel="stylesheet" href="{% static 'authsystem/css/index.css' %}">
{% endblock %}
{% block content %}
<div class="nav">
    <a href="{% url 'authsystem:login_attempt' %}"><button class="register-btn">Login</button></a>

    <!-- <a href="{% url 'authsystem:logout_view' %}"><button class="buttonss">Logout</button></a> -->

    <div class="container">
    <button class="register-btn">Register</button>
    <ul class="dropdown">
      <li>
        <a href="{% url 'authsystem:register_customer' %}"><button class="btn" id="bgcolor">Customer</button></a>
      </li>
      <li>
        <a href="{% url 'authsystem:register_labour' %}"><button class="btn">  Labour  </button></a>
      </li>
    </ul>
</div>
  </div>

{% endblock %}

dailyjob/authsystem/templates/authsystem/login.html
{% extends 'authsystem/base.html' %}

{% load static %}

{% block title %}Login{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'authsystem/css/register_customer.css' %}">
{% endblock %}

{% block content %}

<a href="{% url 'authsystem:index' %}"><button class="index-btn">Home</button></a>
<div class="container">
    <div class="row">
        <div class="col-lg-3 col-md-2"></div>
        <div class="col-lg-6 col-md-8 login-box">
            <div class="col-lg-12 login-key">
                <i class="fa fa-key" aria-hidden="true"></i>
            </div>

            <div class="col-lg-12 login-title">
                LOGIN
            </div>

            <div class="col-lg-12 login-form">
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label class="form-control-label">USERNAME</label>
                        <input type="email" class="form-control" name="username">
                    </div>
                    <div class="form-group">
                        <label class="form-control-label">PASSWORD</label>
                        <input type="password" class="form-control" name="password">
                    </div>
                    <div class="form-group">
                        <label class="form-control-label">ROLE</label>
                        <select name="role" class="form-control">
                            <option value="customer" selected>Customer</option>
                            <option value="labour">Labour</option>
                        </select>
                    </div>

                    <div class="col-lg-6 login-btm login-text">
                        <!-- Error Message -->

                        {% if messages %}
                        <div class="alert alert-danger">
                            <ul class="list-unstyled">
                                {% for message in messages %}
                                <li>{{ message }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                        {% endif %}


                    </div>


                    <div class="col-lg-12 loginbttm">
                        <div class="col-lg-6 login-btm login-button">
                            <button type="submit" class="btn btn-outline-primary">LOGIN</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    {% endblock %}

dailyjob/authsystem/templates/authsystem/register_customer.html
{% extends 'authsystem/base.html' %}

{% load static %}

{% block title %}Customer Registrations{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'authsystem/css/register_customer.css' %}">
{% endblock %}

{% block content %}
<a href="{% url 'authsystem:index' %}"><button class="index-btn">Home</button></a>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-2"></div>
            <div class="col-lg-6 col-md-8 login-box">
                <div class="col-lg-12 login-key">
                    <i class="fa fa-key" aria-hidden="true"></i>
                </div>

                <div class="col-lg-12 login-title">
                    REGISTRATION
                </div>

                <div class="col-lg-12 login-form">
                    <form>
                        <div class="form-group">
                            <label class="form-control-label">USERNAME</label>
                            <input type="email" class="form-control" name="username"
                                placeholder="Use your username as Email">
                        </div>
                        <div class="form-group">
                            <label class="form-control-label">PASSWORD</label>
                            <input type="password" class="form-control" name="password" id="password">
                        </div>

                        <div class="form-group">
                            <label class="form-control-label">CONFIRM PASSWORD</label>
                            <input type="password" class="form-control" name="password" id="confirmPassword">
                        </div>
                        <div class="form-group">
                            <label class="form-control-label">NAME</label>
                            <input type="text" class="form-control" name="name">
                        </div>
                        <div class="form-group">
                            <label class="form-control-label">PHONE NUMBER</label>
                            <input type="text" class="form-control" name="phone_number">
                        </div>
                        <div class="form-group">
                            <label class="form-control-label">ADDRESS</label>
                            <input type="text" class="form-control" name="address">
                        </div>
                        <div class="form-group">
                            <label class="form-control-label">IMAGE</label>
                            <input type="file" class="form-control" name="image">
                        </div>
                        <div class="col-lg-6 login-btm login-text">
                            <!-- Error Message -->

                            {% if messages %}
                            <div class="alert alert-danger">
                                <ul class="list-unstyled">
                                    {% for message in messages %}
                                    <li>{{ message }}</li>
                                    {% endfor %}
                                </ul>
                            </div>
                            {% endif %}


                        </div>


                        <div class="col-lg-12 loginbttm">
                            <div class="col-lg-6 login-btm login-button">
                                <button type="submit" class="btn btn-outline-primary" id="submit">REGISTER</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <input type="hidden" id="alert-flag" value="{% if alert_flag %}true{% else %}false{% endif %}">
</form>

<script src="{% static 'authsystem/js/register_customer.js' %}"></script>


{% endblock %}

dailyjob/authsystem/templates/authsystem/register_labour.html
{% extends 'authsystem/base.html' %}

{% load static %}

{% block title %}Labour Registrations{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'authsystem/css/register_customer.css' %}">
{% endblock %}

{% block content %}
<a href="{% url 'authsystem:index' %}"><button class="index-btn">Home</button></a>

<div class="container">
    <div class="row">

        <div class="col-lg-3 col-md-2"></div>

        <div class="col-lg-6 col-md-8 login-box">
            <div class="col-lg-12 login-title">
                REGISTRATION
            </div>

            <div class="col-lg-12 login-form">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <label class="form-control-label">USERNAME</label>
                        <input type="email" class="form-control" name="username"
                            placeholder="Use your username as Email">
                    </div>
                    <div class="form-group">
                        <label class="form-control-label">PASSWORD</label>
                        <input type="password" class="form-control" name="password" id="password">
                    </div>
                    <div class="form-group">
                        <label class="form-control-label">CONFIRM PASSWORD</label>
                        <input type="password" class="form-control" name="password" id="confirmPassword">
                    </div>
                    <div class="form-group">
                        <label class="form-control-label">NAME</label>
                        <input type="text" class="form-control" name="name">
                    </div>
                    <div class="form-group">
                        <label class="form-control-label">PHONE NUMBER</label>
                        <input type="text" class="form-control" name="phone_number">
                    </div>
                    <div class="form-group">
                        <label class="form-control-label">PLACE</label>
                        <input type="text" class="form-control" name="place">
                    </div>
                    <div class="form-group">
                        <label class="form-control-label">FEES</label>
                        <input type="text" class="form-control" name="fees">
                    </div>
                    <div class="form-group">
                        <label class="form-control-label">IMAGE</label>
                        <input type="file" class="form-control" name="image">
                    </div>


                    <div class="form-group">
                        <label class="form-control-label">PROFESSION</label>
                        <select name="profession" id="profession" onchange="toggleProfessionInput()"
                            class="form-control">
                            <option value=""></option>
                            <option value="plumber">Plumber</option>
                            <option value="electrician">Electrician</option>
                            <option value="coolie">Coolie</option>
                            <option value="other">Other</option>
                        </select>
                        <div class="form-group" id="other-profession" style="display:none;">
                            <label class="form-control-label">OTHER PROFESSION</label>
                            <input type="text" class="form-control" name="other_profession">
                        </div>

                    </div>

                    <div class="col-lg-6 login-btm login-text">
                        <!-- Error Message -->

                        {% if messages %}
                        <div class="alert alert-danger">
                            <ul class="list-unstyled">
                                {% for message in messages %}
                                <li>{{ message }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                        {% endif %}


                    </div>


                    <div class="col-lg-12 loginbttm">
                        <div class="col-lg-6 login-btm login-button">
                            <button type="submit" class="btn btn-outline-primary" id="submit">REGISTER</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-lg-3 col-md-2"></div>
    </div>
    <input type="hidden" id="alert-flag" value="{% if alert_flag %}true{% else %}false{% endif %}">
    </form>
    <script src="{% static 'authsystem/js/register_labour.js' %}"></script>
    {% endblock %}